### ISSUE TITLE
Run as non-root user in Docker

### ISSUE THREAD

**Issue by Eirikr70** [bilde2910/Hauk#217]
Hello,
Are there environment variables I might use in order to run Hauk container with a non-root user ?
Thanks,
Eric

**Comment by schklom** [comment]
in docker-compose:
```yaml
  hauk:
    image: ...
    user: 1000:1000 # replace with user group IDs
```
