### ISSUE TITLE
cant seem to connect to use the docker instance.

### ISSUE THREAD

**Issue by ashjas** [bilde2910/Hauk#66]
Hi,

I followed the docker-compose.yml steps.
I am puzzled how would i connect to the docker hauk server?
I dont intend to use https, so i am just using the docker-compose.yml and the config.php configuration.
But which url i need to access?
Thanks.

**Comment by bilde2910** [comment]
The Docker container listens on port 80. If you don't intend to use a reverse proxy, you have to add a `ports` directive to the compose file for this to be reachable from outside, e.g.

```yaml
services:
  hauk:
    image: bilde2910/hauk
    container_name: hauk
    volumes:
      - ./config/hauk:/etc/hauk
    ports:
      - 8912:80/tcp
```

.. for it to be reachable on port 8912, for example. (`-p 8912:80/tcp` for Docker CLI.) I do strongly recommend HTTPS, however - setting up Let's Encrypt in a reverse proxy is not too difficult, and HTTPS both protects against MITM attacks and eavesdropping, and is required for some functionality like in-browser geolocation on the map, and end-to-end encryption functionality (in some browsers).

When you have added the `ports` directive in the compose file, you can connect to the Hauk server at `http://<docker host IP>:<chosen port>/`.
